name: Build Action

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  getNodeVersion:
    uses: gagoar/ts-node-template/.github/workflows/get_node_version.yml@main

  build:
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - uses: actions/checkout@main
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
