on:
  push:
    branches:
      - renovate/*

name: rebuild dist/ + commit for renovate

jobs:
  getNodeVersion:
    uses: gagoar/ts-node-template/.github/workflows/get_node_version.yml@main

  runCommitPush:
    needs: getNodeVersion
    uses: gagoar/ts-node-template/.github/workflows/run_hook_commit_and_push.yml@main
    secrets:
      token: ${{ secrets.UPDATE_PR_TOKEN }}
    with:
      node_version: ${{ needs.getNodeVersion.outputs.node_version }}
      hook_to_run: npm i && npm run build
