on:
  push:
    branches:
      - renovate/*
      - gg/test-workflow
    # Sequence of patterns matched against refs/tags

name: rebuild dist/ + commit for renovate

jobs:
  getToken:
    runs-on: ubuntu-latest
    outputs:
      TOKEN: ${{ steps.auth.outputs.token }}
    steps:
      - id: auth
        uses: jnwng/github-app-installation-token-action@v2
        with:
          appId: ${{ secrets.UHA_APP_ID }}
          installationId: ${{ secrets.UHA_INSTALLATION_ID }}
          privateKey: ${{ secrets.UHA_APP_PRIVATE_KEY }}

  getNodeVersion:
    uses: gagoar/ts-node-template/.github/workflows/get_node_version.yml@main

  runCommitPush:
    needs: [getToken, getNodeVersion]
    uses: gagoar/ts-node-template/.github/workflows/run_hook_commit_and_push.yml@gg/run-commit-push
    secrets:
      token: ${{ needs.getToken.outputs.TOKEN }}
    with:
      node_version: ${{ needs.getNodeVersion.outputs.node_version }}
      hook_to_run: npm i && npm run build
